### Import Dataset

In [30]:
file = r'C:\Users\paton\Downloads\Dataset for data scientist assessment - Lead.csv'

In [43]:
import pandas as pd 
import re

### Data Exploration
- Explored the dataset to understand its structure and identify missing values.

In [34]:
data = pd.read_csv(file)
data.head()

                               Restaurant name        lat        long
0  Sushi Hiro (ซูชิฮิโระ) Eight Thonglor ชั้น1  13.730788  100.581716
1                          Sushi Hiro พรอมานาด  13.826534  100.676388
2                            ซูชิฮิโระ หองหล่อ  13.730900  100.584720
3               หองหล่อ Sushi Hiro ในตึก Eight  13.730888  100.582816
4                           Hiro Sushi ทองหล่อ  13.730751  100.582316

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Restaurant name  30 non-null     object
 1   lat              30 non-null     float64
 2   long             30 non-null     float64
dtypes: float64(2), object(1)
memory usage: 852.0+ bytes

In [38]:
data.isnull().sum()

Restaurant name    0
lat                0
long               0
dtype: int64

---------------------

### Data Preparation

In [41]:
data['lower_Restaurant_name'] = data['Restaurant name'].apply(lambda x: x.lower().strip())
data.head()

,Restaurant name,lat,long,lower_Restaurant_name
0,Sushi Hiro (ซูชิฮิโระ) Eight Thonglor ชั้น1,13.730788,100.581716,sushi hiro (ซูชิฮิโระ) eight thonglor ชั้น1
1,Sushi Hiro พรอมานาด,13.826534,100.676388,sushi hiro พรอมานาด
2,ซูชิฮิโระ หองหล่อ,13.730900,100.584720,ซูชิฮิโระ หองหล่อ
3,หองหล่อ Sushi Hiro ในตึก Eight,13.730888,100.582816,หองหล่อ sushi hiro ในตึก eight
4,Hiro Sushi ทองหล่อ,13.730751,100.582316,hiro sushi ทองหล่อ

In [55]:
data['remove_special_text'] = data['lower_Restaurant_name'].apply(lambda x: re.sub(r'[^a-zA-Z0-9\u0E00-\u0E7F\s]',"",x))
data.head(10)

,Restaurant name,lat,long,lower_Restaurant_name,remove_special_text
0,Sushi Hiro (ซูชิฮิโระ) Eight Thonglor ชั้น1,13.730788,100.581716,sushi hiro (ซูชิฮิโระ) eight thonglor ชั้น1,sushi hiro ซูชิฮิโระ eight thonglor ชั้น1
1,Sushi Hiro พรอมานาด,13.826534,100.676388,sushi hiro พรอมานาด,sushi hiro พรอมานาด
2,ซูชิฮิโระ หองหล่อ,13.730900,100.584720,ซูชิฮิโระ หองหล่อ,ซูชิฮิโระ หองหล่อ
3,หองหล่อ Sushi Hiro ในตึก Eight,13.730888,100.582816,หองหล่อ sushi hiro ในตึก eight,หองหล่อ sushi hiro ในตึก eight
4,Hiro Sushi ทองหล่อ,13.730751,100.582316,hiro sushi ทองหล่อ,hiro sushi ทองหล่อ
5,Honmono Sushi (ฮอนโมโน ซูชิ) ทองหล่อ,13.738052,100.582191,honmono sushi (ฮอนโมโน ซูชิ) ทองหล่อ,honmono sushi ฮอนโมโน ซูชิ ทองหล่อ
6,ร้าน ซูชิ ฮอนโมโน แถว ทองหล่อ,13.738054,100.583275,ร้าน ซูชิ ฮอนโมโน แถว ทองหล่อ,ร้าน ซูชิ ฮอนโมโน แถว ทองหล่อ
7,Honmono Sushi สาขา เซ็นทรัล บางนา,13.670290,100.635344,honmono sushi สาขา เซ็นทรัล บางนา,honmono sushi สาขา เซ็นทรัล บางนา
8,ร้าน Sushi ฮอนโมโน บางนา,13.671315,100.636435,ร้าน sushi ฮอนโมโน บางนา,ร้าน sushi ฮอนโมโน บางนา
9,Honmono ซูชิ ซอย ทองหล่อ 23,13.738252,100.583231,honmono ซูชิ ซอย ทองหล่อ 23,honmono ซูชิ ซอย ทองหล่อ 23

In [65]:
stopword = ['ร้าน','สาขา','แถว','ซอย','บริษัท','เดอะ']

In [83]:
data['Cleaned_Restaurant_name'] = data['remove_special_text'].apply(lambda x: [word for word in x.split() if word not in stopword])
data['Cleaned_Restaurant_name'] = data['Cleaned_Restaurant_name'].apply(lambda x: " ".join(x))
data.head(10)

,Restaurant name,lat,long,lower_Restaurant_name,remove_special_text,Cleaned_Restaurant_name
0,Sushi Hiro (ซูชิฮิโระ) Eight Thonglor ชั้น1,13.730788,100.581716,sushi hiro (ซูชิฮิโระ) eight thonglor ชั้น1,sushi hiro ซูชิฮิโระ eight thonglor ชั้น1,sushi hiro ซูชิฮิโระ eight thonglor ชั้น1
1,Sushi Hiro พรอมานาด,13.826534,100.676388,sushi hiro พรอมานาด,sushi hiro พรอมานาด,sushi hiro พรอมานาด
2,ซูชิฮิโระ หองหล่อ,13.730900,100.584720,ซูชิฮิโระ หองหล่อ,ซูชิฮิโระ หองหล่อ,ซูชิฮิโระ หองหล่อ
3,หองหล่อ Sushi Hiro ในตึก Eight,13.730888,100.582816,หองหล่อ sushi hiro ในตึก eight,หองหล่อ sushi hiro ในตึก eight,หองหล่อ sushi hiro ในตึก eight
4,Hiro Sushi ทองหล่อ,13.730751,100.582316,hiro sushi ทองหล่อ,hiro sushi ทองหล่อ,hiro sushi ทองหล่อ
5,Honmono Sushi (ฮอนโมโน ซูชิ) ทองหล่อ,13.738052,100.582191,honmono sushi (ฮอนโมโน ซูชิ) ทองหล่อ,honmono sushi ฮอนโมโน ซูชิ ทองหล่อ,honmono sushi ฮอนโมโน ซูชิ ทองหล่อ
6,ร้าน ซูชิ ฮอนโมโน แถว ทองหล่อ,13.738054,100.583275,ร้าน ซูชิ ฮอนโมโน แถว ทองหล่อ,ร้าน ซูชิ ฮอนโมโน แถว ทองหล่อ,ซูชิ ฮอนโมโน ทองหล่อ
7,Honmono Sushi สาขา เซ็นทรัล บางนา,13.670290,100.635344,honmono sushi สาขา เซ็นทรัล บางนา,honmono sushi สาขา เซ็นทรัล บางนา,honmono sushi เซ็นทรัล บางนา
8,ร้าน Sushi ฮอนโมโน บางนา,13.671315,100.636435,ร้าน sushi ฮอนโมโน บางนา,ร้าน sushi ฮอนโมโน บางนา,sushi ฮอนโมโน บางนา
9,Honmono ซูชิ ซอย ทองหล่อ 23,13.738252,100.583231,honmono ซูชิ ซอย ทองหล่อ 23,honmono ซูชิ ซอย ทองหล่อ 23,honmono ซูชิ ทองหล่อ 23

-------------------------------

### Name Matching

- This section uses fuzzy matching to analyze the similarity between restaurant names. The similarity score is calculated using a fuzzy matching function, which returns a value between 0 and 100. A similarity threshold of 80 is applied to determine potential duplicate restaurant names. If the similarity score between two restaurant names is greater than or equal to 80, the pair is considered a potential match and append to name_matching.

In [86]:
from rapidfuzz import fuzz

In [143]:
name_matching = []
Cleaned_Restaurant_name = data['Cleaned_Restaurant_name']

for i in range(len(Cleaned_Restaurant_name)):
    for j in range(i+1,len(Cleaned_Restaurant_name)):
        name_1 = data.loc[i,'Cleaned_Restaurant_name']
        name_2 = data.loc[j,'Cleaned_Restaurant_name']
        score = fuzz.token_ratio(name_1,name_2)
        if score >= 80:
            name_matching.append((i,j,score))
name_matching

[(4, 5, 83.87096774193549),
 (5, 6, 100.0),
 (5, 8, 81.25),
 (5, 9, 93.02325581395348),
 (19, 21, 84.61538461538461),
 (19, 23, 100.0),
 (21, 23, 84.61538461538461),
 (25, 27, 100.0),
 (28, 29, 85.71428571428572)]

**- Precision/Recall trade-offs**

1. A higher threshold (e.g., 90) -> increases precision because only very similar names will be matched and reduced false positives, but can may miss true duplicates with spelling variations.
2. A lower threshold (e.g., 70) -> increases recall by capturing more potential duplicates. However, this may introduce false matches between restaurants with partially similar names.

**So thresholds in the range of 80–85 are often used in practice to balance precision and recall when performing fuzzy name matching.**

--------------------

### Location Matching

In [99]:
from geopy.distance import geodesic

- Location similarity is evaluated using a distance threshold of 200 meters. Restaurant pairs within 200 meters are considered geographically similar.

In [149]:
location_matching = []
for i in range(len(data)):
    for j in range(i+1,len(data)):
        lat_1 = data.loc[i,'lat']
        long_1 = data.loc[i,'long']
        lat_2 = data.loc[j,'lat']
        long_2 = data.loc[j,'long']
        distance = geodesic((lat_1, long_1), (lat_2, long_2)).meters
        if distance <= 200:
            location_matching.append((i,j,distance))
location_matching

[(0, 3, 119.48771146103248),
 (0, 4, 65.02412866213444),
 (3, 4, 56.16324834861066),
 (5, 6, 117.24048721911248),
 (5, 9, 114.63719594433671),
 (6, 9, 22.417051021212227),
 (7, 8, 163.68068668179643),
 (10, 11, 93.52035401826544),
 (10, 13, 106.09006419671994),
 (11, 13, 197.60042912204756),
 (12, 26, 65.07259718015828),
 (16, 18, 0.0),
 (19, 20, 36.48981646820093),
 (19, 21, 58.90183953158851),
 (19, 23, 40.383202620826374),
 (19, 24, 70.80821728137444),
 (20, 21, 46.54212053446211),
 (20, 23, 12.339253620051604),
 (20, 24, 37.61078239449619),
 (21, 23, 58.76326903696707),
 (21, 24, 74.68050921624442),
 (23, 24, 30.425263496430105),
 (25, 26, 187.4142960121549),
 (25, 27, 22.01549266818528),
 (25, 28, 46.6110712705024),
 (25, 29, 9.396817107385814),
 (26, 27, 166.36575726769937),
 (26, 28, 142.12602199182928),
 (26, 29, 178.07392680893497),
 (27, 28, 24.70461489268039),
 (27, 29, 13.775805504508003),
 (28, 29, 37.78620496853021)]

-----------------------------------------

### Combined Matching & Evaluation

**name_similarlity_score**

In [159]:
name_similarlity_score = []
Cleaned_Restaurant_name = data['Cleaned_Restaurant_name']

for i in range(len(Cleaned_Restaurant_name)):
    for j in range(i+1,len(Cleaned_Restaurant_name)):
        name_1 = data.loc[i,'Cleaned_Restaurant_name']
        name_2 = data.loc[j,'Cleaned_Restaurant_name']
        score = fuzz.token_ratio(name_1,name_2)
        name_similarlity_score.append((i,j,score))
name_similarlity_score

[(0, 1, 68.9655172413793),
 (0, 2, 69.23076923076923),
 (0, 3, 69.56521739130434),
 (0, 4, 71.42857142857143),
 (0, 5, 48.0),
 (0, 6, 19.672131147540984),
 (0, 7, 46.3768115942029),
 (0, 8, 41.666666666666664),
 (0, 9, 34.375),
 (0, 10, 20.33898305084746),
 (0, 11, 23.728813559322038),
 (0, 12, 26.229508196721312),
 (0, 13, 16.129032258064512),
 (0, 14, 29.85074626865672),
 (0, 15, 16.949152542372886),
 (0, 16, 10.344827586206895),
 (0, 17, 25.0),
 (0, 18, 15.094339622641513),
 (0, 19, 28.57142857142857),
 (0, 20, 16.438356164383563),
 (0, 21, 17.85714285714286),
 (0, 22, 25.71428571428571),
 (0, 23, 23.33333333333333),
 (0, 24, 16.393442622950815),
 (0, 25, 35.95505617977528),
 (0, 26, 21.818181818181813),
 (0, 27, 21.818181818181813),
 (0, 28, 14.54545454545455),
 (0, 29, 14.54545454545455),
 (1, 2, 11.111111111111116),
 (1, 3, 68.9655172413793),
 (1, 4, 71.42857142857143),
 (1, 5, 45.28301886792453),
 (1, 6, 25.64102564102564),
 (1, 7, 51.06382978723405),
 (1, 8, 52.63157894736842),
 (1, 9, 23.809523809523814),
 (1, 10, 37.83783783783784),
 (1, 11, 32.432432432432435),
 (1, 12, 35.8974358974359),
 (1, 13, 15.000000000000002),
 (1, 14, 35.55555555555556),
 (1, 15, 27.02702702702703),
 (1, 16, 16.66666666666667),
 (1, 17, 29.411764705882348),
 (1, 18, 19.354838709677423),
 (1, 19, 25.80645161290323),
 (1, 20, 23.529411764705888),
 (1, 21, 17.647058823529417),
 (1, 22, 25.0),
 (1, 23, 15.789473684210531),
 (1, 24, 20.512820512820518),
 (1, 25, 23.880597014925375),
 (1, 26, 24.24242424242425),
 (1, 27, 24.24242424242425),
 (1, 28, 18.181818181818187),
 (1, 29, 24.24242424242425),
 (2, 3, 58.333333333333336),
 (2, 4, 40.0),
 (2, 5, 43.13725490196079),
 (2, 6, 59.45945945945946),
 (2, 7, 13.33333333333333),
 (2, 8, 16.66666666666667),
 (2, 9, 55.00000000000001),
 (2, 10, 17.14285714285714),
 (2, 11, 11.428571428571432),
 (2, 12, 5.405405405405405),
 (2, 13, 15.789473684210531),
 (2, 14, 18.604651162790702),
 (2, 15, 11.428571428571432),
 (2, 16, 17.647058823529417),
 (2, 17, 6.25),
 (2, 18, 13.793103448275868),
 (2, 19, 13.33333333333333),
 (2, 20, 16.326530612244895),
 (2, 21, 6.25),
 (2, 22, 17.391304347826093),
 (2, 23, 5.555555555555558),
 (2, 24, 16.216216216216218),
 (2, 25, 3.07692307692308),
 (2, 26, 6.451612903225811),
 (2, 27, 6.451612903225811),
 (2, 28, 19.354838709677423),
 (2, 29, 12.903225806451616),
 (3, 4, 71.42857142857143),
 (3, 5, 53.125),
 (3, 6, 36.0),
 (3, 7, 41.379310344827594),
 (3, 8, 41.666666666666664),
 (3, 9, 41.509433962264154),
 (3, 10, 37.5),
 (3, 11, 37.5),
 (3, 12, 32.0),
 (3, 13, 19.607843137254903),
 (3, 14, 25.0),
 (3, 15, 25.0),
 (3, 16, 17.021276595744684),
 (3, 17, 31.111111111111114),
 (3, 18, 19.04761904761905),
 (3, 19, 30.136986301369863),
 (3, 20, 22.580645161290324),
 (3, 21, 17.777777777777782),
 (3, 22, 27.118644067796616),
 (3, 23, 20.40816326530613),
 (3, 24, 16.000000000000004),
 (3, 25, 28.205128205128204),
 (3, 26, 18.181818181818187),
 (3, 27, 18.181818181818187),
 (3, 28, 13.63636363636364),
 (3, 29, 13.63636363636364),
 (4, 5, 83.87096774193549),
 (4, 6, 56.0),
 (4, 7, 47.82608695652174),
 (4, 8, 43.47826086956522),
 (4, 9, 56.0),
 (4, 10, 38.888888888888886),
 (4, 11, 33.333333333333336),
 (4, 12, 36.8421052631579),
 (4, 13, 15.384615384615387),
 (4, 14, 31.818181818181824),
 (4, 15, 22.22222222222223),
 (4, 16, 17.14285714285714),
 (4, 17, 30.303030303030297),
 (4, 18, 20.0),
 (4, 19, 22.95081967213115),
 (4, 20, 16.000000000000004),
 (4, 21, 18.181818181818187),
 (4, 22, 21.276595744680847),
 (4, 23, 16.216216216216218),
 (4, 24, 15.789473684210531),
 (4, 25, 21.212121212121218),
 (4, 26, 18.75),
 (4, 27, 25.0),
 (4, 28, 18.75),
 (4, 29, 18.75),
 (5, 6, 100.0),
 (5, 7, 63.41463414634146),
 (5, 8, 81.25),
 (5, 9, 93.02325581395348),
 (5, 10, 38.46153846153846),
 (5, 11, 30.769230769230774),
 (5, 12, 29.629629629629633),
 (5, 13, 21.818181818181813),
 (5, 14, 30.000000000000004),
 (5, 15, 19.23076923076923),
 (5, 16, 19.607843137254903),
 (5, 17, 20.40816326530613),
 (5, 18, 17.391304347826093),
 (5, 19, 28.57142857142857),
 (5, 20, 24.24242424242425),
 (5, 21, 12.244897959183676),
 (5, 22, 25.396825396825395),
 (5, 23, 18.867924528301884),
 (5, 24, 18.518518518518523),
 (5, 25, 29.268292682926834),
 (5, 26, 25.0),
 (5, 27, 25.0),
 (5, 28, 16.66666666666667),
 (5, 29, 16.66666666666667),
 (6, 7, 16.66666666666667),
 (6, 8, 53.84615384615385),
 (6, 9, 75.0),
 (6, 10, 26.315789473684216),
 (6, 11, 15.789473684210531),
 (6, 12, 10.0),
 (6, 13, 24.390243902439025),
 (6, 14, 17.391304347826093),
 (6, 15, 21.05263157894737),
 (6, 16, 21.621621621621628),
 (6, 17, 11.428571428571432),
 (6, 18, 12.5),
 (6, 19, 19.04761904761905),
 (6, 20, 26.923076923076927),
 (6, 21, 11.428571428571432),
 (6, 22, 24.489795918367353),
 (6, 23, 10.256410256410263),
 (6, 24, 25.0),
 (6, 25, 8.82352941176471),
 (6, 26, 11.764705882352944),
 (6, 27, 11.764705882352944),
 (6, 28, 23.529411764705888),
 (6, 29, 23.529411764705888),
 (7, 8, 73.33333333333333),
 (7, 9, 47.05882352941177),
 (7, 10, 30.434782608695656),
 (7, 11, 30.434782608695656),
 (7, 12, 33.333333333333336),
 (7, 13, 16.326530612244895),
 (7, 14, 33.333333333333336),
 (7, 15, 26.086956521739136),
 (7, 16, 17.777777777777782),
 (7, 17, 23.25581395348837),
 (7, 18, 25.0),
 (7, 19, 33.80281690140845),
 (7, 20, 23.33333333333333),
 (7, 21, 13.953488372093027),
 (7, 22, 35.08771929824562),
 (7, 23, 21.276595744680847),
 (7, 24, 29.16666666666667),
 (7, 25, 28.947368421052634),
 (7, 26, 28.57142857142857),
 (7, 27, 28.57142857142857),
 (7, 28, 23.809523809523814),
 (7, 29, 28.57142857142857),
 (8, 9, 19.04761904761905),
 (8, 10, 32.432432432432435),
 (8, 11, 27.02702702702703),
 (8, 12, 15.384615384615387),
 (8, 13, 25.0),
 (8, 14, 31.111111111111114),
 (8, 15, 27.02702702702703),
 (8, 16, 22.22222222222223),
 (8, 17, 23.529411764705888),
 (8, 18, 25.80645161290323),
 (8, 19, 22.580645161290324),
 (8, 20, 23.529411764705888),
 (8, 21, 17.647058823529417),
 (8, 22, 29.16666666666667),
 (8, 23, 10.526315789473685),
 (8, 24, 30.769230769230774),
 (8, 25, 20.895522388059707),
 (8, 26, 18.181818181818187),
 (8, 27, 18.181818181818187),
 (8, 28, 30.303030303030297),
 (8, 29, 36.36363636363637),
 (9, 10, 29.268292682926834),
 (9, 11, 29.268292682926834),
 (9, 12, 27.906976744186053),
 (9, 13, 18.181818181818187),
 (9, 14, 24.489795918367353),
 (9, 15, 24.390243902439025),
 (9, 16, 20.0),
 (9, 17, 21.05263157894737),
 (9, 18, 17.14285714285714),
 (9, 19, 24.24242424242425),
 (9, 20, 18.181818181818187),
 (9, 21, 21.05263157894737),
 (9, 22, 26.923076923076927),
 (9, 23, 19.04761904761905),
 (9, 24, 13.953488372093027),
 (9, 25, 25.352112676056336),
 (9, 26, 27.02702702702703),
 (9, 27, 21.621621621621628),
 (9, 28, 16.216216216216218),
 (9, 29, 16.216216216216218),
 (10, 11, 50.0),
 (10, 12, 36.8421052631579),
 (10, 13, 75.86206896551724),
 (10, 14, 50.0),
 (10, 15, 38.888888888888886),
 (10, 16, 28.57142857142857),
 (10, 17, 30.303030303030297),
 (10, 18, 26.66666666666667),
 (10, 19, 32.786885245901644),
 (10, 20, 28.000000000000004),
 (10, 21, 18.181818181818187),
 (10, 22, 34.04255319148937),
 (10, 23, 16.216216216216218),
 (10, 24, 26.315789473684216),
 (10, 25, 21.212121212121218),
 (10, 26, 18.75),
 (10, 27, 25.0),
 (10, 28, 18.75),
 (10, 29, 18.75),
 (11, 12, 36.8421052631579),
 (11, 13, 15.384615384615387),
 (11, 14, 50.0),
 (11, 15, 44.44444444444444),
 (11, 16, 17.14285714285714),
 (11, 17, 42.42424242424242),
 (11, 18, 26.66666666666667),
 (11, 19, 26.229508196721312),
 (11, 20, 12.0),
 (11, 21, 24.24242424242425),
 (11, 22, 21.276595744680847),
 (11, 23, 27.02702702702703),
 (11, 24, 10.526315789473685),
 (11, 25, 24.24242424242425),
 (11, 26, 18.75),
 (11, 27, 25.0),
 (11, 28, 18.75),
 (11, 29, 18.75),
 (12, 13, 9.756097560975608),
 (12, 14, 30.434782608695656),
 (12, 15, 36.36363636363637),
 (12, 16, 5.405405405405405),
 (12, 17, 51.42857142857143),
 (12, 18, 31.25),
 (12, 19, 25.396825396825395),
 (12, 20, 11.538461538461542),
 (12, 21, 34.28571428571429),
 (12, 22, 20.40816326530613),
 (12, 23, 30.769230769230774),
 (12, 24, 10.0),
 (12, 25, 41.1764705882353),
 (12, 26, 23.529411764705888),
 (12, 27, 47.05882352941177),
 (12, 28, 11.764705882352944),
 (12, 29, 11.764705882352944),
 (13, 14, 60.0),
 (13, 15, 30.769230769230774),
 (13, 16, 47.36842105263158),
 (13, 17, 11.111111111111116),
 (13, 18, 18.181818181818187),
 (13, 19, 25.0),
 (13, 20, 30.188679245283023),
 (13, 21, 11.111111111111116),
 (13, 22, 32.0),
 (13, 23, 10.0),
 (13, 24, 34.14634146341463),
 (13, 25, 5.797101449275366),
 (13, 26, 11.428571428571432),
 (13, 27, 11.428571428571432),
 (13, 28, 34.28571428571429),
 (13, 29, 34.28571428571429),
 (14, 15, 45.45454545454546),
 (14, 16, 38.095238095238095),
 (14, 17, 24.390243902439025),
 (14, 18, 42.10526315789474),
 (14, 19, 26.086956521739136),
 (14, 20, 17.24137931034483),
 (14, 21, 19.512195121951223),
 (14, 22, 25.454545454545453),
 (14, 23, 13.33333333333333),
 (14, 24, 26.086956521739136),
 (14, 25, 21.621621621621628),
 (14, 26, 20.0),
 (14, 27, 20.0),
 (14, 28, 25.0),
 (14, 29, 25.0),
 (15, 16, 57.142857142857146),
 (15, 17, 42.10526315789474),
 (15, 18, 40.0),
 (15, 19, 22.95081967213115),
 (15, 20, 20.0),
 (15, 21, 18.181818181818187),
 (15, 22, 25.531914893617028),
 (15, 23, 16.216216216216218),
 (15, 24, 21.05263157894737),
 (15, 25, 18.181818181818187),
 (15, 26, 25.0),
 (15, 27, 18.75),
 (15, 28, 18.75),
 (15, 29, 18.75),
 (16, 17, 6.25),
 (16, 18, 20.689655172413794),
 (16, 19, 13.33333333333333),
 (16, 20, 24.489795918367353),
 (16, 21, 6.25),
 (16, 22, 17.391304347826093),
 (16, 23, 5.555555555555558),
 (16, 24, 21.621621621621628),
 (16, 25, 6.15384615384616),
 (16, 26, 6.451612903225811),
 (16, 27, 6.451612903225811),
 (16, 28, 19.354838709677423),
 (16, 29, 19.354838709677423),
 (17, 18, 37.03703703703704),
 (17, 19, 27.58620689655173),
 (17, 20, 8.510638297872347),
 (17, 21, 33.333333333333336),
 (17, 22, 18.181818181818187),
 (17, 23, 35.294117647058826),
 (17, 24, 11.428571428571432),
 (17, 25, 28.57142857142857),
 (17, 26, 34.48275862068966),
 (17, 27, 34.48275862068966),
 (17, 28, 13.793103448275868),
 (17, 29, 13.793103448275868),
 (18, 19, 18.181818181818187),
 (18, 20, 13.63636363636364),
 (18, 21, 22.22222222222223),
 (18, 22, 19.512195121951223),
 (18, 23, 25.80645161290323),
 (18, 24, 12.5),
 (18, 25, 20.0),
 (18, 26, 30.769230769230774),
 (18, 27, 30.769230769230774),
 (18, 28, 15.384615384615387),
 (18, 29, 15.384615384615387),
 (19, 20, 51.16279069767442),
 (19, 21, 84.61538461538461),
 (19, 22, 75.0),
 (19, 23, 100.0),
 (19, 24, 70.96774193548387),
 (19, 25, 37.362637362637365),
 (19, 26, 44.44444444444444),
 (19, 27, 44.44444444444444),
 (19, 28, 21.05263157894737),
 (19, 29, 44.44444444444444),
 (20, 21, 8.510638297872347),
 (20, 22, 55.0),
 (20, 23, 7.843137254901967),
 (20, 24, 70.96774193548387),
 (20, 25, 15.000000000000002),
 (20, 26, 13.043478260869568),
 (20, 27, 8.695652173913048),
 (20, 28, 30.434782608695656),
 (20, 29, 44.44444444444444),
 (21, 22, 42.10526315789474),
 (21, 23, 84.61538461538461),
 (21, 24, 11.428571428571432),
 (21, 25, 42.10526315789474),
 (21, 26, 44.44444444444444),
 (21, 27, 55.172413793103445),
 (21, 28, 13.793103448275868),
 (21, 29, 13.793103448275868),
 (22, 23, 34.78260869565217),
 (22, 24, 73.46938775510205),
 (22, 25, 28.57142857142857),
 (22, 26, 44.44444444444444),
 (22, 27, 44.44444444444444),
 (22, 28, 27.906976744186053),
 (22, 29, 44.44444444444444),
 (23, 24, 10.256410256410263),
 (23, 25, 41.791044776119406),
 (23, 26, 44.44444444444444),
 (23, 27, 44.44444444444444),
 (23, 28, 12.121212121212125),
 (23, 29, 12.121212121212125),
 (24, 25, 5.882352941176472),
 (24, 26, 11.764705882352944),
 (24, 27, 11.764705882352944),
 (24, 28, 35.294117647058826),
 (24, 29, 44.44444444444444),
 (25, 26, 78.26086956521739),
 (25, 27, 100.0),
 (25, 28, 6.451612903225811),
 (25, 29, 6.451612903225811),
 (26, 27, 78.26086956521739),
 (26, 28, 44.44444444444444),
 (26, 29, 21.42857142857143),
 (27, 28, 14.285714285714292),
 (27, 29, 14.285714285714292),
 (28, 29, 85.71428571428572)]

----------------------------------

**location_similarity_score**

In [161]:
location_similarity_score = []
for i in range(len(data)):
    for j in range(i+1,len(data)):
        lat_1 = data.loc[i,'lat']
        long_1 = data.loc[i,'long']
        lat_2 = data.loc[j,'lat']
        long_2 = data.loc[j,'long']
        distance = geodesic((lat_1, long_1), (lat_2, long_2)).meters
        score = max(0, 100 * (1 - distance/200))
        location_similarity_score.append((i,j,score))
location_similarity_score

[(0, 1, 0),
 (0, 2, 0),
 (0, 3, 40.25614426948376),
 (0, 4, 67.48793566893279),
 (0, 5, 0),
 (0, 6, 0),
 (0, 7, 0),
 (0, 8, 0),
 (0, 9, 0),
 (0, 10, 0),
 (0, 11, 0),
 (0, 12, 0),
 (0, 13, 0),
 (0, 14, 0),
 (0, 15, 0),
 (0, 16, 0),
 (0, 17, 0),
 (0, 18, 0),
 (0, 19, 0),
 (0, 20, 0),
 (0, 21, 0),
 (0, 22, 0),
 (0, 23, 0),
 (0, 24, 0),
 (0, 25, 0),
 (0, 26, 0),
 (0, 27, 0),
 (0, 28, 0),
 (0, 29, 0),
 (1, 2, 0),
 (1, 3, 0),
 (1, 4, 0),
 (1, 5, 0),
 (1, 6, 0),
 (1, 7, 0),
 (1, 8, 0),
 (1, 9, 0),
 (1, 10, 0),
 (1, 11, 0),
 (1, 12, 0),
 (1, 13, 0),
 (1, 14, 0),
 (1, 15, 0),
 (1, 16, 0),
 (1, 17, 0),
 (1, 18, 0),
 (1, 19, 0),
 (1, 20, 0),
 (1, 21, 0),
 (1, 22, 0),
 (1, 23, 0),
 (1, 24, 0),
 (1, 25, 0),
 (1, 26, 0),
 (1, 27, 0),
 (1, 28, 0),
 (1, 29, 0),
 (2, 3, 0),
 (2, 4, 0),
 (2, 5, 0),
 (2, 6, 0),
 (2, 7, 0),
 (2, 8, 0),
 (2, 9, 0),
 (2, 10, 0),
 (2, 11, 0),
 (2, 12, 0),
 (2, 13, 0),
 (2, 14, 0),
 (2, 15, 0),
 (2, 16, 0),
 (2, 17, 0),
 (2, 18, 0),
 (2, 19, 0),
 (2, 20, 0),
 (2, 21, 0),
 (2, 22, 0),
 (2, 23, 0),
 (2, 24, 0),
 (2, 25, 0),
 (2, 26, 0),
 (2, 27, 0),
 (2, 28, 0),
 (2, 29, 0),
 (3, 4, 71.91837582569467),
 (3, 5, 0),
 (3, 6, 0),
 (3, 7, 0),
 (3, 8, 0),
 (3, 9, 0),
 (3, 10, 0),
 (3, 11, 0),
 (3, 12, 0),
 (3, 13, 0),
 (3, 14, 0),
 (3, 15, 0),
 (3, 16, 0),
 (3, 17, 0),
 (3, 18, 0),
 (3, 19, 0),
 (3, 20, 0),
 (3, 21, 0),
 (3, 22, 0),
 (3, 23, 0),
 (3, 24, 0),
 (3, 25, 0),
 (3, 26, 0),
 (3, 27, 0),
 (3, 28, 0),
 (3, 29, 0),
 (4, 5, 0),
 (4, 6, 0),
 (4, 7, 0),
 (4, 8, 0),
 (4, 9, 0),
 (4, 10, 0),
 (4, 11, 0),
 (4, 12, 0),
 (4, 13, 0),
 (4, 14, 0),
 (4, 15, 0),
 (4, 16, 0),
 (4, 17, 0),
 (4, 18, 0),
 (4, 19, 0),
 (4, 20, 0),
 (4, 21, 0),
 (4, 22, 0),
 (4, 23, 0),
 (4, 24, 0),
 (4, 25, 0),
 (4, 26, 0),
 (4, 27, 0),
 (4, 28, 0),
 (4, 29, 0),
 (5, 6, 41.37975639044376),
 (5, 7, 0),
 (5, 8, 0),
 (5, 9, 42.68140202783165),
 (5, 10, 0),
 (5, 11, 0),
 (5, 12, 0),
 (5, 13, 0),
 (5, 14, 0),
 (5, 15, 0),
 (5, 16, 0),
 (5, 17, 0),
 (5, 18, 0),
 (5, 19, 0),
 (5, 20, 0),
 (5, 21, 0),
 (5, 22, 0),
 (5, 23, 0),
 (5, 24, 0),
 (5, 25, 0),
 (5, 26, 0),
 (5, 27, 0),
 (5, 28, 0),
 (5, 29, 0),
 (6, 7, 0),
 (6, 8, 0),
 (6, 9, 88.79147448939389),
 (6, 10, 0),
 (6, 11, 0),
 (6, 12, 0),
 (6, 13, 0),
 (6, 14, 0),
 (6, 15, 0),
 (6, 16, 0),
 (6, 17, 0),
 (6, 18, 0),
 (6, 19, 0),
 (6, 20, 0),
 (6, 21, 0),
 (6, 22, 0),
 (6, 23, 0),
 (6, 24, 0),
 (6, 25, 0),
 (6, 26, 0),
 (6, 27, 0),
 (6, 28, 0),
 (6, 29, 0),
 (7, 8, 18.159656659101785),
 (7, 9, 0),
 (7, 10, 0),
 (7, 11, 0),
 (7, 12, 0),
 (7, 13, 0),
 (7, 14, 0),
 (7, 15, 0),
 (7, 16, 0),
 (7, 17, 0),
 (7, 18, 0),
 (7, 19, 0),
 (7, 20, 0),
 (7, 21, 0),
 (7, 22, 0),
 (7, 23, 0),
 (7, 24, 0),
 (7, 25, 0),
 (7, 26, 0),
 (7, 27, 0),
 (7, 28, 0),
 (7, 29, 0),
 (8, 9, 0),
 (8, 10, 0),
 (8, 11, 0),
 (8, 12, 0),
 (8, 13, 0),
 (8, 14, 0),
 (8, 15, 0),
 (8, 16, 0),
 (8, 17, 0),
 (8, 18, 0),
 (8, 19, 0),
 (8, 20, 0),
 (8, 21, 0),
 (8, 22, 0),
 (8, 23, 0),
 (8, 24, 0),
 (8, 25, 0),
 (8, 26, 0),
 (8, 27, 0),
 (8, 28, 0),
 (8, 29, 0),
 (9, 10, 0),
 (9, 11, 0),
 (9, 12, 0),
 (9, 13, 0),
 (9, 14, 0),
 (9, 15, 0),
 (9, 16, 0),
 (9, 17, 0),
 (9, 18, 0),
 (9, 19, 0),
 (9, 20, 0),
 (9, 21, 0),
 (9, 22, 0),
 (9, 23, 0),
 (9, 24, 0),
 (9, 25, 0),
 (9, 26, 0),
 (9, 27, 0),
 (9, 28, 0),
 (9, 29, 0),
 (10, 11, 53.23982299086728),
 (10, 12, 0),
 (10, 13, 46.95496790164003),
 (10, 14, 0),
 (10, 15, 0),
 (10, 16, 0),
 (10, 17, 0),
 (10, 18, 0),
 (10, 19, 0),
 (10, 20, 0),
 (10, 21, 0),
 (10, 22, 0),
 (10, 23, 0),
 (10, 24, 0),
 (10, 25, 0),
 (10, 26, 0),
 (10, 27, 0),
 (10, 28, 0),
 (10, 29, 0),
 (11, 12, 0),
 (11, 13, 1.1997854389762197),
 (11, 14, 0),
 (11, 15, 0),
 (11, 16, 0),
 (11, 17, 0),
 (11, 18, 0),
 (11, 19, 0),
 (11, 20, 0),
 (11, 21, 0),
 (11, 22, 0),
 (11, 23, 0),
 (11, 24, 0),
 (11, 25, 0),
 (11, 26, 0),
 (11, 27, 0),
 (11, 28, 0),
 (11, 29, 0),
 (12, 13, 0),
 (12, 14, 0),
 (12, 15, 0),
 (12, 16, 0),
 (12, 17, 0),
 (12, 18, 0),
 (12, 19, 0),
 (12, 20, 0),
 (12, 21, 0),
 (12, 22, 0),
 (12, 23, 0),
 (12, 24, 0),
 (12, 25, 0),
 (12, 26, 67.46370140992086),
 (12, 27, 0),
 (12, 28, 0),
 (12, 29, 0),
 (13, 14, 0),
 (13, 15, 0),
 (13, 16, 0),
 (13, 17, 0),
 (13, 18, 0),
 (13, 19, 0),
 (13, 20, 0),
 (13, 21, 0),
 (13, 22, 0),
 (13, 23, 0),
 (13, 24, 0),
 (13, 25, 0),
 (13, 26, 0),
 (13, 27, 0),
 (13, 28, 0),
 (13, 29, 0),
 (14, 15, 0),
 (14, 16, 0),
 (14, 17, 0),
 (14, 18, 0),
 (14, 19, 0),
 (14, 20, 0),
 (14, 21, 0),
 (14, 22, 0),
 (14, 23, 0),
 (14, 24, 0),
 (14, 25, 0),
 (14, 26, 0),
 (14, 27, 0),
 (14, 28, 0),
 (14, 29, 0),
 (15, 16, 0),
 (15, 17, 0),
 (15, 18, 0),
 (15, 19, 0),
 (15, 20, 0),
 (15, 21, 0),
 (15, 22, 0),
 (15, 23, 0),
 (15, 24, 0),
 (15, 25, 0),
 (15, 26, 0),
 (15, 27, 0),
 (15, 28, 0),
 (15, 29, 0),
 (16, 17, 0),
 (16, 18, 100.0),
 (16, 19, 0),
 (16, 20, 0),
 (16, 21, 0),
 (16, 22, 0),
 (16, 23, 0),
 (16, 24, 0),
 (16, 25, 0),
 (16, 26, 0),
 (16, 27, 0),
 (16, 28, 0),
 (16, 29, 0),
 (17, 18, 0),
 (17, 19, 0),
 (17, 20, 0),
 (17, 21, 0),
 (17, 22, 0),
 (17, 23, 0),
 (17, 24, 0),
 (17, 25, 0),
 (17, 26, 0),
 (17, 27, 0),
 (17, 28, 0),
 (17, 29, 0),
 (18, 19, 0),
 (18, 20, 0),
 (18, 21, 0),
 (18, 22, 0),
 (18, 23, 0),
 (18, 24, 0),
 (18, 25, 0),
 (18, 26, 0),
 (18, 27, 0),
 (18, 28, 0),
 (18, 29, 0),
 (19, 20, 81.75509176589954),
 (19, 21, 70.54908023420575),
 (19, 22, 0),
 (19, 23, 79.80839868958681),
 (19, 24, 64.59589135931279),
 (19, 25, 0),
 (19, 26, 0),
 (19, 27, 0),
 (19, 28, 0),
 (19, 29, 0),
 (20, 21, 76.72893973276895),
 (20, 22, 0),
 (20, 23, 93.83037318997421),
 (20, 24, 81.19460880275192),
 (20, 25, 0),
 (20, 26, 0),
 (20, 27, 0),
 (20, 28, 0),
 (20, 29, 0),
 (21, 22, 0),
 (21, 23, 70.61836548151646),
 (21, 24, 62.6597453918778),
 (21, 25, 0),
 (21, 26, 0),
 (21, 27, 0),
 (21, 28, 0),
 (21, 29, 0),
 (22, 23, 0),
 (22, 24, 0),
 (22, 25, 0),
 (22, 26, 0),
 (22, 27, 0),
 (22, 28, 0),
 (22, 29, 0),
 (23, 24, 84.78736825178494),
 (23, 25, 0),
 (23, 26, 0),
 (23, 27, 0),
 (23, 28, 0),
 (23, 29, 0),
 (24, 25, 0),
 (24, 26, 0),
 (24, 27, 0),
 (24, 28, 0),
 (24, 29, 0),
 (25, 26, 6.292851993922555),
 (25, 27, 88.99225366590736),
 (25, 28, 76.69446436474881),
 (25, 29, 95.30159144630709),
 (26, 27, 16.817121366150324),
 (26, 28, 28.93698900408537),
 (26, 29, 10.963036595532516),
 (27, 28, 87.64769255365981),
 (27, 29, 93.112097247746),
 (28, 29, 81.1068975157349)]

----------------------------------------

- Combine score with solution :  ***final_score = (0.3 x name_similarlity_score) + (0.7 x location_similarity_score)***
  
In this approach, a higher weight is assigned to location similarity because restaurant names can sometimes be inconsistent due to spelling variations, abbreviations, or formatting differences. For example, the same restaurant may appear as “Sushi Hiro”, “Sushi Hero”, or “Sushi Hiro Thonglor”.

Location information, on the other hand, tends to be more stable and reliable for identifying the same physical restaurant. Therefore, location similarity is given a higher weight (0.7), while name similarity is given a lower weight (0.3).

In [194]:
final_similarity_score = []

Cleaned_Restaurant_name = data['Cleaned_Restaurant_name']

for i in range(len(Cleaned_Restaurant_name)):
    for j in range(i+1,len(Cleaned_Restaurant_name)):
        name_1 = data.loc[i,'Cleaned_Restaurant_name']
        name_2 = data.loc[j,'Cleaned_Restaurant_name']
        name_score = fuzz.token_ratio(name_1,name_2)

        lat_1 = data.loc[i,'lat']
        long_1 = data.loc[i,'long']
        lat_2 = data.loc[j,'lat']
        long_2 = data.loc[j,'long']
        distance = geodesic((lat_1, long_1), (lat_2, long_2)).meters
        location_score = max(0, 100 * (1 - distance/200))

        final_score = (0.3*name_score)+(0.7*location_score)
        if final_score >=80:
            final_similarity_score.append((i,j,final_score))
final_similarity_score

[(6, 9, 84.65403214257572),
 (19, 23, 85.86587908271076),
 (25, 27, 92.29457756613515),
 (28, 29, 82.48911397530014)]

-------------------------

### Describe evaluation metrics (precision, recall, F1-score)

- **Precision** measures the proportion of predicted duplicate restaurant pairs that are actually correct.
- **Recall** measures the proportion of true duplicate restaurants that the system successfully identifies.
- **F1-score** combines precision and recall into a single metric to evaluate the overall performance of the duplicate detection system.